apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: db-deploy
    type: test-d
  name: db-svc
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  
  selector:
      type: test-d
  type: ClusterIP
status:
  loadBalancer: {}
