apiVersion: apps/v1
kind: Deployment
metadata:
   name: meal-plan-deployment
   labels:
      app: mp-deploy
      type: test-m

spec:
   template:
      metadata:
         name: mp-app
         labels:
            type: test-m
      spec:
         containers:
         - name: meal-plan-container
           image: akashdro/meal_plan_ruby
           ports:
           - containerPort: 3000       
           env:
           - name: POSTGRES_USER
             value: "akash"
           - name: POSTGRES_PASSWORD
             value: "abcd1234"
           - name: POSTGRES_DB
             value: "db"
           - name: POSTGRES_HOST
             value: "db"
           
   replicas: 1
   selector:
      matchLabels:
         type: test-m
