apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mp-deploy
    type: test-m
  name: load-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
#    nodePort: 30005
  selector:
    type: test-m
  type: LoadBalancer
status:
  loadBalancer: {}
